#include<iostream>
usingnamespacestd;
classnode
{
public:
intkey;
node*next;
node*previous;
stringname;
intyears;
floatamount;
stringcontact;
stringmore;
node()
{
key=0;
intyears=0;
floatamount=0;
next=NULL;
previous=NULL;
}
node(intk1,stringiname,stringpcontact,stringimore,inty1,float
iamount)
{
name=iname;
contact=pcontact;
more=imore;
years=y1;
amount=iamount;
key=k1;
}
};
classonline
{
public:
node*head;
online()
{
head=NULL;
}
online(node*n)
{
head=n;
}
node*existnode(intk)
{
node*temp=NULL;
node*ptr=head;
while(ptr!=NULL)
{
if(ptr->key==k)
{
temp=ptr;
}
ptr=ptr->next;
}
returntemp;
}
voidpriority_home_appliances(node*h)
{
if(existnode(h->key)!=NULL)
{
cout<<"alreadyhaveaitemwithsamekey:->"<<h
->key<<endl;
cout<<"firstdeletethisofferforshow
another"<<endl;
}
else
{
if(head==NULL)
{
head=h;
h->next=NULL;
cout<<"inserted"<<endl;
}
else
{
h->next=head;
head->previous=h;
head=h;
}
}
}
voidinsert_home_appliances(node*h)
{
if(existnode(h->key)!=NULL)
{
cout<<"alreadyhaveaiteminsamekey:->"<<h
->key<<"trydifferentone"<<endl;
}
else
{
if(head==NULL)
{
head=h;
h->next=NULL;
cout<<"headinserted"<<endl;
}
else
{
node*ptr=head;
while(ptr->next!=NULL)
{
ptr=ptr->next;
}
ptr->next=h;
h->next=NULL;
h->previous=ptr;
cout<<"iteminserted"<<endl;
}
}
}
voidpriority_vehicles(node*v)
{
if(existnode(v->key)!=NULL)
{
cout<<"alreadyhaveaitemwithsamekey:"<<v
->key<<endl;
}
else
{
if(head==NULL)
{
head=v;
v->next=NULL;
cout<<"inserted"<<endl;
}
else
{
v->next=head;
head->previous=v;
head=v;
}
}
}
voidinsert_vehicles(node*v)
{
if(existnode(v->key)!=NULL)
{
cout<<"alreadyhaveaiteminsamekey:"<<v
->key<<"trydifferentone"<<endl;
}
else
{
if(head==NULL)
{
head=v;
v->next=NULL;
cout<<"headinserted"<<endl;
}
else
{
node*ptr=head;
while(ptr->next!=NULL)
{
ptr=ptr->next;
}
ptr->next=v;
v->next=NULL;
v->previous=ptr;
cout<<"iteminserted"<<endl;
}
}
}
voidpriority_electronics(node*e)
{
if(existnode(e->key)!=NULL)
{
cout<<"alreadyhaveaitemwithsamekey:->"<<e
->key<<endl;
}
else
{
if(head==NULL)
{
head=e;
e->next=NULL;
cout<<"inserted"<<endl;
}
else
{
e->next=head;
head->previous=e;
head=e;
}
}
}
voidinsert_electronics(node*e)
{
if(existnode(e->key)!=NULL)
{
cout<<"alreadyhaveaiteminsamekey:->"<<e
->key<<"trydifferentone"<<endl;
}
else
{
if(head==NULL)
{
head=e;
e->next=NULL;
cout<<"headinserted"<<endl;
}
else
{
node*ptr=head;
while(ptr->next!=NULL)
{
ptr=ptr->next;
}
ptr->next=e;
e->next=NULL;
e->previous=ptr;
cout<<"iteminserted"<<endl;
}
}
}
voidupdate(intk,stringnewiname,stringnewpcontact,string
newimore,intnewy1,floatnewiamount)
{
node*ptr=existnode(k);
if(ptr==NULL)
{
cout<<"nonodeexist";
}
else
{
ptr->contact=newpcontact;
ptr->more=newimore;
ptr->name=newiname;
ptr->amount=newiamount;
ptr->years=newy1;
cout<<"itemsdetailsupdated"<<endl<<endl;
}
}
voiddelete_priority(intk)
{
node*ptr=existnode(k);
if(ptr==NULL)
{
cout<<"nonodewithpriorityfound:->"<<k<<endl;
}
else
{
if(head->key==k)
{
cout<<"unlinkingoperationstarts"<<endl;
node*temp=ptr->next;
temp->previous=NULL;
temp=head;
cout<<"nodeunlinked"<<endl<<endl;
}
}
}
voiddeleteitem(intk)
{
node*ptr=existnode(k);
if(ptr==NULL)
{
cout<<"nonodefoundwihtkey"<<endl<<endl;
}
else
{
if(head->key==k)
{
head=head->next;
cout<<"nodeunlinked:"<<k<<endl;
}
else
{
node*nextnode=ptr->next;
node*prenode=ptr->previous;
if(nextnode==NULL)
{
prenode->next=NULL;
cout<<"deleted"<<endl<<endl;
}
else
{
prenode->next=nextnode;
nextnode->previous=prenode;
cout<<"deleted"<<endl<<endl;
}
}
}
}
void display()
{
if(head==NULL)
{
cout<<"itisempty"<<endl;
}
else
{
cout<<"theitemsareasfollows:"<<endl;
node*temp=head;
intpage=0;
while(temp!=NULL)
{
page+=1;
cout<<"pagenumberis:"<<page<<endl<<endl;
cout<<"keyis:"<<temp->key<<endl<<endl;
cout<<"itemnameis:"<<temp
->name<<endl<<endl;
cout<<"amountis:"<<temp
->amount<<endl<<endl;
cout<<"numberofyearsusedis:"<<temp
->years<<endl<<endl;
cout<<"moreabouttheitem:"<<temp
->more<<endl<<endl;
cout<<"contact"<<temp->contact<<endl<<endl;
temp=temp->next;
}
}
}
voidsearch(intk)
{
node*ptr=existnode(k);
if(ptr=NULL)
{
cout<<"nonodeexistwihtkey:"<<k<<endl;
}
else
{
if(head->key==k)
{
node*temp=head;
cout<<"itemfound"<<endl;
cout<<"keyis:"<<temp->key<<endl<<endl;
cout<<"itemnameis:"<<temp
->name<<endl<<endl;
cout<<"amountis:"<<temp
->amount<<endl<<endl;
cout<<"numberofyearsusedis:"<<temp
->years<<endl<<endl;
cout<<"moreabouttheitem:"<<temp
->more<<endl<<endl;
cout<<"contact"<<temp->contact<<endl<<endl;
}
else
{
node*temp=ptr;
cout<<"itemfound"<<endl;
cout<<"keyis:"<<temp->key<<endl<<endl;
cout<<"itemnameis:"<<temp
->name<<endl<<endl;
cout<<"amountis:"<<temp
->amount<<endl<<endl;
cout<<"numberofyearsusedis:"<<temp
->years<<endl<<endl;
cout<<"moreabouttheitem:"<<temp
->more<<endl<<endl;
cout<<"contact"<<temp->contact<<endl<<endl;
}
}
}
};
Int main()
{
Online o;
int k,ys,m;
float am;
string con;
string mor;
string nam;
menu:
node*h1;
node*v1;
node*e1;
cout<<"\n1.inserthomeapp\n2.insertingvehicles\n3.forinserting
electronics\n4.priorityvehicles\n5.prioityelectronics\n6.priorityhome
app\n7.updateforitems\n8.display\n9.delete
item\n10.deletepriority\n11.search\n12.clearscreen\n13.exit"<<endl;
cout<<"entertheoptiontoselect"<<endl;
cin>>m;
switch(m)
{
case1:
h1=newnode();
cout<<"USEEVENKEYSFORHOMEAPPLIANCES"<<endl;
cout<<"ENTERTHEKEYVALUE";
cin>>k;
if(k%2==0)
{
cout<<"ENTERTHENUMBEROFYEARSTHATTHEITEM
HADBEENUSED:"<<endl;
cin>>ys;
cout<<"ENTERTHEFINALAMOUNTOFTHEITEMNOW:
"<<endl;
cin>>am;
cin.ignore();
cout<<"ENTERTHENAMEOFTHEITEM"<<endl;
getline(cin,nam);
cin.ignore();
cout<<"ENTERMOREDETAILSABOUTTHE
ITEM,ACCORDINGTOTHECORRESPONDINGITEM"<<endl;
getline(cin,mor);
cin.ignore();
cout<<"ENTERTHEMOBILENUMBEROFTHEOWNERTO
CONTACT"<<endl;
getline(cin,con);
h1->amount=am;
h1->years=ys;
h1->contact=con;
h1->more=mor;
h1->name=nam;
h1->key=k;
o.insert_home_appliances(h1);
goto menu;
}
else
{
cout<<"WRONGKEYVALUEENTERED!!!!TRY
AGAIN!!!"<<endl;
goto menu;
}
case2:
v1=newnode();
cout<<"USEODDKEYVALUESFORUPLOADINGYOUR
VEHICLESDETAILS"<<endl;
cout<<"ENTERTHEKEYVALUE"<<endl;
cin>>k;
if(k%2==1)
{
cout<<"ENTERTHENUMBEROFYEARSTHATTHEITEM
HADBEENUSED:"<<endl;
cin>>ys;
cout<<"ENTERTHEFINALAMOUNTOFTHEITEMNOW:
"<<endl;
cin>>am;
cin.ignore();
cout<<"ENTERTHENAMEOFTHEITEM"<<endl;
getline(cin,nam);
cin.ignore();
cout<<"ENTERMOREDETAILSABOUTTHE
ITEM,ACCORDINGTOTHECORRESPONDINGITEM"<<endl;
getline(cin,mor);
cin.ignore();
cout<<"ENTERTHEPHONEORMOBILENUMBEROFTHE
OWNERTOCONTACT"<<endl;
getline(cin,con);
v1->amount=am;
v1->years=ys;
v1->contact=con;
v1->more=mor;
v1->name=nam;
v1->key=k;
o.insert_vehicles(v1);
goto menu;
}
else
{
cout<<"SORRYYOUHAVEENTEREDWRONGKEY
VALUES!!!!TRYAGAIN!!!!"<<endl;
gotomenu;
}
case3:
e1=newnode();
cout<<"USENEGATIVEKEYVALUESFORYOUR
ELECTRONICSUPLOADINGDETAILS"<<endl;
cout<<"ENTERTHEKEYVALUE"<<endl;
cin>>k;
if(k<0)
{
cout<<"ENTERTHENUMBEROFYEARSTHATTHEITEM
HADBEENUSED:"<<endl;
cin>>ys;
cout<<"ENTERTHEFINALAMOUNTOFTHEITEMNOW:
"<<endl;
cin>>am;
cin.ignore();
cout<<"ENTERTHENAMEOFTHEITEM"<<endl;
getline(cin,nam);
cin.ignore();
cout<<"ENTERMOREDETAILSABOUTTHE
ITEM,ACCORDINGTOTHECORRESPONDINGITEM"<<endl;
getline(cin,mor);
cin.ignore();
cout<<"ENTERTHEPHONEORMOBILENUMBEROFTHE
OWNERTOCONTACT"<<endl;
getline(cin,con);
e1->amount=am;
e1->years=ys;
e1->contact=con;
e1->more=mor;
e1->name=nam;
e1->key=k;
o.insert_electronics(e1);
goto menu;
}
else
{
cout<<"SORRYYOUHAVEENTEREDWRONGKEY
VALUES!!!!TRYAGAIN!!!!"<<endl;
Goto menu;
}
case4:
h1=newnode();
cout<<"use0keyvalueforshowyourdetailsis
priority"<<endl;
cout<<"ENTERTHEKEYVALUE"<<endl;
cin>>k;
if(k==0)
{
cout<<"ENTERTHENUMBEROFYEARSTHATTHEITEM
HADBEENUSED:"<<endl;
cin>>ys;
cout<<"ENTERTHEFINALAMOUNTOFTHEITEMNOW:
"<<endl;
cin>>am;
cin.ignore();
cout<<"ENTERTHENAMEOFTHEITEM"<<endl;
getline(cin,nam);
cin.ignore();
cout<<"ENTERMOREDETAILSABOUTTHE
ITEM,ACCORDINGTOTHECORRESPONDINGITEM"<<endl;
getline(cin,mor);
cin.ignore();
cout<<"ENTERTHEPHONEORMOBILENUMBEROFTHE
OWNERTOCONTACT"<<endl;
getline(cin,con);
h1->amount=am;
h1->years=ys;
h1->contact=con;
h1->more=mor;
h1->name=nam;
h1->key=k;
o.priority_home_appliances(h1);
goto menu;
}
else
{
cout<<"SORRYYOUHAVEENTEREDWRONGKEY
VALUES!!!!TRYAGAIN!!!!"<<endl;
goto menu;
}
case5:
v1=newnode();
cout<<"use0keyvalueforshowyourdetailsis
priority"<<endl;
cout<<"ENTERTHEKEYVALUE"<<endl;
cin>>k;
if(k==0)
{
cout<<"ENTERTHENUMBEROFYEARSTHATTHEITEM
HADBEENUSED:"<<endl;
cin>>ys;
cout<<"ENTERTHEFINALAMOUNTOFTHEITEMNOW:
"<<endl;
cin>>am;
cin.ignore();
cout<<"ENTERTHENAMEOFTHEITEM"<<endl;
getline(cin,nam);
cin.ignore();
cout<<"ENTERMOREDETAILSABOUTTHE
ITEM,ACCORDINGTOTHECORRESPONDINGITEM"<<endl;
getline(cin,mor);
cin.ignore();
cout<<"ENTERTHEPHONEORMOBILENUMBEROFTHE
OWNERTOCONTACT"<<endl;
getline(cin,con);
v1->amount=am;
v1->years=ys;
v1->contact=con;
v1->more=mor;
v1->name=nam;
v1->key=k;
o.priority_vehicles(v1);
gotomenu;
}
else
{
cout<<"SORRYYOUHAVEENTEREDWRONGKEY
VALUES!!!!TRYAGAIN!!!!"<<endl;
goto menu;
}
case6:
e1=newnode();
cout<<"use0keyvalueforshowyourdetailsis
priority"<<endl;
cout<<"ENTERTHEKEYVALUE"<<endl;
cin>>k;
if(k==0)
{
cout<<"ENTERTHENUMBEROFYEARSTHATTHEITEM
HADBEENUSED:"<<endl;
cin>>ys;
cout<<"ENTERTHEFINALAMOUNTOFTHEITEMNOW:
"<<endl;
cin>>am;
cin.ignore();
cout<<"ENTERTHENAMEOFTHEITEM"<<endl;
getline(cin,nam);
cin.ignore();
cout<<"ENTERMOREDETAILSABOUTTHE
ITEM,ACCORDINGTOTHECORRESPONDINGITEM"<<endl;
getline(cin,mor);
cin.ignore();
cout<<"ENTERTHEPHONEORMOBILENUMBEROFTHE
OWNERTOCONTACT"<<endl;
getline(cin,con);
e1->amount=am;
e1->years=ys;
e1->contact=con;
e1->more=mor;
e1->name=nam;
e1->key=k;
o.priority_electronics(e1);
goto menu;
}
else
{
cout<<"SORRYYOUHAVEENTEREDWRONGKEY
VALUES!!!!TRYAGAIN!!!!"<<endl;
Goto menu;
}
case7:
cout<<"forupdationuse\n1.evenkeyforhome
app\n2.oddkeyforvehicles\n3negativeintegersforelectronics"<<endl;
cout<<"ETNERTHEKEYVALUE"<<endl;
cin>>k;
cout<<"ENTERTHENUMBEROFYEARSTHATTHEITEM
HADBEENUSED:"<<endl;
cin>>ys;
cout<<"ENTERTHEFINALAMOUNTOFTHEITEMNOW:
"<<endl;
cin>>am;
cin.ignore();
cout<<"ENTERTHENAMEOFTHEITEM"<<endl;
getline(cin,nam);
cin.ignore();
cout<<"ENTERMOREDETAILSABOUTTHE
ITEM,ACCORDINGTOTHECORRESPONDINGITEM"<<endl;
getline(cin,mor);
cin.ignore();
cout<<"ENTERTHEPHONEORMOBILENUMBEROFTHE
OWNERTOCONTACT"<<endl;
getline(cin,con);
o.update(k,nam,con,mor,ys,am);
goto menu;
case8:
o.display();
goto menu;
case9:
cout<<"1.evenkeyforhomeapp\n2.oddkeyfor
vehicles\n3.negativeforelectronics"<<endl;
cout<<"ENTERTHEKEYTODELETENODE"<<endl;
cin>>k;
o.deleteitem(k);
goto menu;
case10:
cout<<"priorityofferdeletingcalled"<<endl;
cout<<"enter0fordeletingpriority"<<endl;
cout<<"entethekey"<<endl;
cin>>k;
if(k==0)
{
o.delete_priority(k);
goto menu;
}
else
{
cout<<"SORRYYOUHAVEENTEREDWRONGKEY
VALUES!!!!TRYAGAIN!!!!"<<endl;
goto menu;
}
case11:
cout<<"1.evenkeyforhomeapp\n2.oddkeyfor
vehicles\n3.negativeforelectronics"<<endl;
cout<<"ENTERTHEKEYFORSEARCH"<<endl;
cin>>k;
o.search(k);
goto menu;
case12:
goto menu;
case13:
cout<<"exit"<<endl;
goto menu;
default:
break;
}
Return 0;
}
